### ISSUE TITLE
Can't run main.py

### ISSUE THREAD

**Issue by Ghosflot** [harmonoid/harmonoid-music-bot#6]
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from commands.playback import Playback
  File "/root/m/commands/playback.py", line 10
    if not (server := await Server.get(ctx)):
                   ^
SyntaxError: invalid syntax

**Comment by mytja** [comment]
You have to use Python 3.7 or above.

Let me know if issue persists.

**Comment by Ghosflot** [comment]
Yep, I already noticed, thought it was some code error. Thanks for the response!
